### ISSUE TITLE
Ability to install unsafe eboot as safe

### ISSUE THREAD

**Issue by coderobe** [TheOfficialFloW/VitaShell#111]
Make it possible to change the flag in the eboot to 2 after installing the package 

Somewhat like this: 
![2016-10-02-152851](https://cloud.githubusercontent.com/assets/8442384/19020973/23ce915e-88b7-11e6-9aaf-6f598d869a5b.jpg)

**Comment by coderobe** [comment]
After `Install as safe` is clicked, it should probably prompt the user for confirmation again, stating that it may break homebrew that actually needs extended permissions.

**Comment by yifanlu** [comment]
This might give users a false sense of security. We actively encourage all developers to mark their eboots as safe unless they need unsafe features. Once a critical mass of homebrews are safe, we might be able to implement more sophisticated checks (like a warning prompt on launch) which would otherwise be annoying if a large percentage of vpks are not marked as safe. Having this might discourage that effort as users will just be used to clicking a button and if we discover any new threats, we might not be able to just patch one byte and fix it--but users would be used to seeing that message and just bypassing the security alert.

**Comment by coderobe** [comment]
Then how about an entry in the (upcoming) settings menu, lets say `Unsafe features`, that - when active - enables the `Install as safe`. This would make it easier for people that know what they're doing, whilst not showing it to people that don't have it active

**Comment by TheOfficialFloW** [comment]
I agree with @yifanlu. If you know what you're doing and you can simply hexedit the flag in the eboot.bin after installation using the integrated hex editor.
