### ISSUE TITLE
Playstation Vita lossless .Vitashell update?

### ISSUE THREAD

**Issue by bastunas** [TheOfficialFloW/VitaShell#224]
Hello , i need to play lossless quality music on psvita . Vita have wolfson dac and mp3 format is not enought...
Vitashell is really good program but i thing need just one update to lossless music and psv will show what they have :)

**Comment by bastunas** [comment]
why closed?

**Comment by joel16** [comment]
I think it's because GitHub isn't some kind of support forum. You can't just go around requesting ideas, unless the developer is fine with that. Also this tab is mainly used for reporting issues with logs or bugs that can be reproduced so that the developer can become aware of them, and publish fixes.

**Comment by bastunas** [comment]
i not understand some people making request with vitashell ...probably my is not good :D  but i hope some day i can play lossless in my vita :)

**Comment by d3m3vilurr** [comment]
@bastunas DO NOT LEAVE F**KING STUPID ISSUE.

although you just want lossless format, that reason does not make permit your stupid actions.

1. project manager can select their project feature and priority
2. you can't.
3. stupid action does not help for the feature. in fact, they make harm.
