### ISSUE TITLE
Mounting ux0 to USB when using sd2vita doesn't work.

### ISSUE THREAD

**Issue by Duckbuster** [TheOfficialFloW/VitaShell#253]
It gives error 0x80244112 when no original vita card is inserted.
When you insert a vita memorycard it mounts that instead of the sd card in the gamecard slot.

I've tried selecting mount gamecard, but that just prompts, please insert a gamecard.

**Comment by Duckbuster** [comment]
I can access it fine over FTP btw.

**Comment by TideGear** [comment]
I can confirm this issue too.

**Comment by manofsteel2017** [comment]
same issue. hopefully flow can help
very excited to have micro SD support. bought  a 128GB cheap

**Comment by hyjinx187** [comment]
+1 Same issue.  I've heard folks suggest that moving the sd card back and forth between the pc and vita is a valid workaround, but this seems to create corruption, likely because of the way windows is handling the card and the sheer volume of rw were doing to it.  Once this is fixed, I intend to wipe my cards and start fresh, leaving the card in the vita at all times and avoiding removing it at all costs.  FTP is too slow to be a viable workaround at the moment.  We're counting on you TheFloW!  Thanks for all you do!

**Comment by mathieulh** [comment]
I can confirm this issue happens on my unit as well.

**Comment by Marcone698** [comment]
Hi all, same problem for me, Vitashell mount uma0 as USB (for me it's PSVita original memory) but I would like mount ux0 (SD card)

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/9385a487066c624b433255ce1177b145bf0ec0b9
