### ISSUE TITLE
Clear pfs mounted path at umount

### ISSUE THREAD

**Issue by TheOfficialFloW** [TheOfficialFloW/VitaShell#284]

**Comment by GrassHydra** [comment]
Your request has been logged. I think I can write here about my mounting issues with Linux.
#question - Why I get 
Error mounting /dev/sdb at /media/admin/232F-15B0: Command-line `mount -t "exfat" -o "uhelper=udisks2,nodev,nosuid,uid=1001,gid=1002,iocharset=utf8,namecase=0,errors=remount-ro,umask=0077" "/dev/sdb" "/media/admin/232F-15B0"' exited with non-zero exit status 32: mount: unknown filesystem type 'exfat' ?
You don't have to answer if it can be fixed by using the latest Vitashell and manual inputting of the commands into Terminal. You could simply build me and others a script. Furthermore,
#enhancement
Fix both memory card and usb-formatted memory cards for pstv automated mounting process if possible
#bug
My 32 gb usb otg Sony stick treats me about the same way my 32 gb Sony card does :
Error mounting /dev/sdb at /media/admin/FE59-128D: Command-line `mount -t "exfat" -o "uhelper=udisks2,nodev,nosuid,uid=1001,gid=1002,iocharset=utf8,namecase=0,errors=remount-ro,umask=0077" "/dev/sdb" "/media/admin/FE59-128D"' exited with non-zero exit status 32: mount: unknown filesystem type 'exfat'
If there's something for me to do I may agree to do it.
If it's about waiting for you to fix the issue from within VitaShell I'll wait.
1 Tb hard drive without splitted game files is accepted by 4.81 CFW, mounts ok in Linux and grants me full access automatically. It has a faster mount speed than it has on Windows, hence the change.

**Comment by TheOfficialFloW** [comment]
Nah I was talking about something else. This issue was just a note to myself

**Comment by GrassHydra** [comment]
Ok guess I have to live with the limitations of wi-fi transfers from now on when using vitashell. Not that scary after all, when you think it's only 802.11n that sets the limit. It's just the limit doubles sometimes, I cannot see why it does that but it cannot go worse than twice the limit, right ?

**Comment by TheOfficialFloW** [comment]
https://github.com/TheOfficialFloW/VitaShell/commit/5a376ca464ac7bd4db75f88d4ca6cd2ba5abfd53
