### ISSUE TITLE
mount ux0: causes app to crash and fail to mount usb

### ISSUE THREAD

**Issue by deadair3210** [TheOfficialFloW/VitaShell#290]
I have a PSTV running 1.74, and I am having trouble with mounting my usb drive as ux0. VitaShell is able to mount the drive as uma0 perfectly fine every time, but for some reason, almost every time that I try to mount it as ux0, it errors out as C1-2755-9.

PSTV 3.60 running latest version of Henkaku Enso
VitaShell 1.74
SanDisk Crusier 32GB
8GB Vita Mem Card

**Comment by kozarovv** [comment]
I think that's because of secret partition on your USB stick. Iirc this model have partition called "U3" with CDFS. Probably success of mounting depend on which partition is ready at first. 

Use different drive, or try this solution: https://kb.sandisk.com/app/answers/detail/a_id/2550/~/removing%2Funinstalling-u3-launchpad-on-a-pc

**Comment by deadair3210** [comment]
Nope, I already checked that both with the tool and with Ubuntu, the only partition on this drive is a exFAT partition which takes up the entirety of the drive. As far as I know, the U3 system doesn't support my drive. Any other ideas?

**Comment by deadair3210** [comment]
Update: I seem to have found the issue. Used Application Storage Manager to move VitaShell onto the internal memory card and the problem seems to have gone away. Not sure if this is a required step and I just missed it or what, but everything seems to work fine now
