### ISSUE TITLE
Visual glitch in Electron theme with "Refresh license database"

### ISSUE THREAD

**Issue by JohnVeness** [TheOfficialFloW/VitaShell#316]
Since 1.76 and the new top-level context menu item "Refresh license database", the menu background isn't wide enough to contain the text in the Electron theme.
![dsc_0606](https://user-images.githubusercontent.com/2512915/32146582-680e4324-bcd1-11e7-894d-fd14ccdaf54b.JPG)

**Comment by 1upus** [comment]
I have the same glitches with long strings with russian translation.

**Comment by szpieg-z-krainy-deszczowcow** [comment]
This happening because last pixel on the right is now multiplicate. To be honest, the whole skinning system is bad designed (mess with filenames, no control over bitmap and size for context menus).

**Comment by Acemad** [comment]
Fixed, I just sent the files to @TheOfficialFloW !
It turns out, I had to make context and context_more 960 pixel large. (thx to theFlow for the tip)
Also fixed the context_more height.

![img_20171231_211356](https://user-images.githubusercontent.com/5701168/34464020-04e64032-ee70-11e7-9ecd-e363f1b49e36.jpg)
![img_20171231_211431](https://user-images.githubusercontent.com/5701168/34464021-050fda1e-ee70-11e7-8993-864ebbfdb812.jpg)

**Comment by TheOfficialFloW** [comment]
Fixed in https://github.com/TheOfficialFloW/VitaShell/commit/6f790862d612cd1493ad27bd83fdfd23d192ea76
