### ISSUE TITLE
Version 1.9 Banned Message

### ISSUE THREAD

**Issue by wilhitewarrior** [TheOfficialFloW/VitaShell#412]
I installed vitashell 1.9 on my playstation tv, running henkaku firmware 3.60 with enso installed
When I did it gave me a message about a violation of ToS, you're banned, etc. Fortunately, my account wasn't linked to the console so obviously nothing happened. Reverted back to version 1.75 (cuz I saw that one working on a youtube video) and it worked fine

**Comment by Conan179a** [comment]
dude we have the 1.4...

**Comment by richard1222** [comment]
I got that to your not really banned btw use this vpk called tsoi from vita homebrowser and move the neareboot.bin after  you rename it to eboot.bin to vitashell it should fix your ban issue that you have  then you can use it again

**Comment by richard1222** [comment]
If you go though with this it will put you on vitashell v1.8 thats why i said to update after moving the eboot to the folder

**Comment by TheOfficialFloW** [comment]
Wait 1min on that ban screen

**Comment by edale2** [comment]
Given the number of issues posted about this, and the number of people who ended up downgrading their VitaShell because of it... I wonder if TheFlow still thinks that April Fools joke was funny? Or perhaps it's in the "Never Again" category? lol.

To be fair, I had a nice laugh... Once I actually figured it out, lol.

**Comment by wilhitewarrior** [comment]
lol I honestly didn't even think about it being April Fools Day. *Facepalm* okay yeah it was kinda funny. lol
