### ISSUE TITLE
failed! 0x804331075

### ISSUE THREAD

**Issue by WindbreakerHD** [TheOfficialFloW/VitaShell#456]
I get this error failed! 0x804331075 when I try to install vita shell

**Comment by TheOfficialFloW** [comment]
Wrong repo.

**Comment by BenChoad** [comment]
(Duplicated my comment from #458)

I had the same issue yesterday across all of my devices. I finally managed to fix this issue by connecting my vita to my mobile hotspot rather than my router, and it worked instantly.

Restarting my router, using a friends etc did nothing to help (although we both use the same ISP, so may be related?)

**Comment by sweeching** [comment]
If anyone using h-encore to install vitashell and it failed with this code, follow this guide (it worked for me with PS TV FW 3.68): https://psvitamod.com/vitashell/

Basically use Qcma to allow Vita's content manager to connect via USB cable, and use PSImgTools' easy installer to install the vitashell via Qcma transfer. Good luck.
