### ISSUE TITLE
Directory renaming fails when renaming 'word' as same uppercase 'WORD'

### ISSUE THREAD

**Issue by benclaff** [TheOfficialFloW/VitaShell#61]
I noticed a bug happening whether a file is renamed from inside vitashell or via FTP renaming.
This happened in ux0:/data. I used vitashell 0.95 on a vita TV and renamed files in the internal memory (1gb).
I had a directory ux0:/data/gg and wanted to rename it ux0:/data/GG .
When validating the renaming nothing happens and the filename stays the same (i.e. ux0:/data/gg).

**Comment by limyz** [comment]
All files or folders are treated as the same filename whether its lower or uppercase. If there's a need to rename it to uppercase, simply add another character to the rear then rename it again in uppercase.

Due to program logic, this behavior works as intended and is presently not an issue nor it affects users critically.
