### ISSUE TITLE
Use cases for "calculate sha1" function?

### ISSUE THREAD

**Issue by persona5** [TheOfficialFloW/VitaShell#85]
If it is there only to compare files and check integrity of transfers, I see no reason to not replace it with CRC32 or Adler which should be _much_ faster on bigger files (collisions though). 
- [ ] Allow Adler32 calculation
- [ ] Allow CRC32 calculation
- [ ] Allow MD5 calculation

**Comment by limyz** [comment]
Seconded. It can be complimented with CRC32 for speed.

**Comment by TheOfficialFloW** [comment]
Be free to change it :)

**Comment by persona5** [comment]
As there are no objections, I will replace sha1 hashing with CRC checksum.

**Comment by littlebalup** [comment]
keep both. And why not add MD5 as well?

**Comment by limyz** [comment]
Personal note to use sceGzipCrc32 and sceZlibAdler32

**Comment by TheOfficialFloW** [comment]
Still requested?

**Comment by limyz** [comment]
Currently WIP. No ETA on current status.

**Comment by devnoname120** [comment]
Has anyone actually used this feature?

**Comment by sergiogamboa2** [comment]
It is an awesome feature to check the validity of the files, only idiots have not used it... Example: Nand dumps

**Comment by xperia64** [comment]
I'm not sure that CPU is the bottleneck here so I don't believe that something simpler like CRC32 would be any faster. I believe that I/O is likely the bottleneck. The main reason I went with SHA1 when I implemented this feature is because VitaShell already had support for it built it. I suppose there's a chance that CRC32 might be less power consuming but I'm not certain.
